config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'cars#index'

  resources :cars
  # resources :cars do
  #   get :show, on: :collection
  # end
end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # before_action :set_car, only: [:show]
  before_action :set_car, only: [:edit, :update]

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to root_path,
        :notice => "#{@car.year} #{@car.make} #{@car.model} created"
    else
      # do something
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to cars_path, notice: "#{@car.year} #{@car.make} #{@car.model} updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_path, notice: "#{@car.year} #{@car.make} #{@car.model} deleted." }
    end
  end

  private
  def car_params
    params.require(:car).permit([:year, :make, :model, :price])
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |form| %>

  <div class="field">
    <%= form.label :make %><br>
    <%= form.text_field :make %>
  </div>
  <div class="field">
    <%= form.label :model %><br>
    <%= form.text_field :model %>
  </div>
  <div class="field">
    <%= form.label :year %><br>
    <%= form.text_field :year %>
  </div>
  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h2>Editing car</h2>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table style="border: 1px; width: 60%">
  <thead>
  <tr>
    <th>make</th>
    <th>model</th>
    <th>year</th>
    <th>price</th>
    <th colspan="3"></th>
  </tr>
</thead>

  <tbody>
  <!--<table id="car_table">-->
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= number_to_currency(car.price) %></td>
        <td><%= link_to 'Edit car', edit_car_path(car) %></td>
        <td><%= link_to 'Show car', car %></td>
        <td><%= link_to 'Destroy car', car, method: :delete, data: { confirm: 'Are you really sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

  <br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h2>New Car</h2>

<%= form_for(@car) do |form| %>
  <p>
    <%= form.label :make %>
    <%= form.text_field :make %>
  </p>
  <p>
    <%= form.label :model %>
    <%= form.text_field :model %>
  </p>
  <p>
    <%= form.label :year %>
    <%= form.text_field :year %>
  </p>
  <p>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </p>
  <%= form.submit %>
<% end %>

app/views/cars/show.html.erb
<h2>View car</h2>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price.number_to_currency %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DavinciMotors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |type, message| %>
  <div class='<%= type %>'>
    <%= message %>
  </div>
<% end %>

<%= yield %>

</body>
</html>